In [ ]:
#!pip install geobr geopandas

In [14]:
import geopandas as gpd
import geobr as geobr
# Carregar os dados geográficos dos municípios brasileiros
municipios = geobr.read_municipality()  
#tipo de dado: geodataframe

municipios.head()

,code_muni,name_muni,code_state,abbrev_state,geometry
0,1100015.0,Alta Floresta D'oeste,11.0,RO,"MULTIPOLYGON (((-62.2462 -11.90149, -62.24151 ..."
1,1100023.0,Ariquemes,11.0,RO,"MULTIPOLYGON (((-63.13712 -9.78413, -63.09013 ..."
2,1100031.0,Cabixi,11.0,RO,"MULTIPOLYGON (((-60.52408 -13.32137, -60.37161..."
3,1100049.0,Cacoal,11.0,RO,"MULTIPOLYGON (((-61.42679 -11.11376, -61.429 -..."
4,1100056.0,Cerejeiras,11.0,RO,"MULTIPOLYGON (((-61.41347 -13.23417, -61.42603..."

In [ ]:
pbs = geobr.read_municipality(code_muni="PA", year=2024)  
#pbs.to_file("municipios_PA.shp")  # cria .shp + arquivos auxiliares
#salva o arquivo .shp e os arquivos auxiliares na pasta atual

pbs.to_file("municipios_PA.gpkg", driver="GPKG", layer="municipios_PA")

In [3]:
df_lookup = geobr.lookup_muni("Parauapebas")

df_lookup.head()

,code_muni,name_muni,code_state,name_state,abbrev_state,code_micro,name_micro,code_meso,name_meso,code_immediate,name_immediate,code_intermediate,name_intermediate
239,1505536,Parauapebas,15,ParÃ¡,PA,15019,Parauapebas,1506,Sudeste Paraense,150010,Parauapebas,1503,MarabÃ¡

In [6]:
#